### ISSUE TITLE
Review for frontend side.

### ISSUE THREAD

**Issue by Crypto-zombie** [Hediousbeast/react-project#2]
I have completed reviewing your project and as a developer who prioritizes clean code, security, and performance, I have noticed several issues from my perspective.

**1**. I am interested in the current project structure. Typically, web projects follow the MVC (Model-View-Controller) pattern where the Model (database) is managed by the Controller (backend). However, it appears that your previous developer attempted to integrate the Firebase database directly from the frontend. While this is feasible for serverless platforms, this project has backend logic and there is code attempting to interact with the database. It seems that the developer may have aimed for simplicity in handling all aspects of the project.
![1-config](https://github.com/user-attachments/assets/7f4ea29b-12da-4a23-ad0e-8f947b73baa1)
![1-database](https://github.com/user-attachments/assets/59bdd070-c876-4b6d-a19b-ebfda17f7728)
![1-model](https://github.com/user-attachments/assets/3cb09b6a-20a3-4f06-b0bb-553f392377cc)

**2.** In terms of the codebase, this frontend section comprises 5 distinct parts: assets, components, fonts, helpers, and pages. However, I am considering restructuring this codebase. 
I believe the "assets" section should incorporate a "fonts" folder, as fonts are also considered assets. Additionally, I propose adding a "layouts" folder, housing three files named "header", "footer", and "mainbody".

Moving forward, all files for React components should be saved as either .jsx or .tsx, refraining from .js. While there may not be any compilation issues even with .js files, maintaining consistency with the specified file formats is recommended.

I have observed that the developer attempted to implement SCSS for styling components; however, no empty file was found. While writing SCSS may require more time, it can greatly aid in understanding and organizing the code and style. To expedite development, junior developers may consider skipping SCSS for now.

Currently, the styles in place are written using pure CSS, which can be improved. I suggest utilizing tailwindcss for more efficient styling.

In some cases, integration with APIs may present challenges due to data structure differences. To mitigate these issues, most developers leverage typescript.

Finaly, I recommend to use React.js(or Next.js) + Typscrtip + Tailwindcss + SCSS + Zustand(or Redux).
![2-fileformat](https://github.com/user-attachments/assets/37a856a6-3e26-4221-b4cc-ccab71a2150c)
![2-scss empty](https://github.com/user-attachments/assets/283dca6d-0c71-4185-a75d-3bd7530e76ce)
![2-structure](https://github.com/user-attachments/assets/ccfc501c-fe92-4dfe-a537-bcbf6c849920)
**3.** Regarding to the fundamentals of Security Principles. When developing a project, it is crucial to securely store sensitive keys, such as apikeys, storageBucket, and private keys. Many developers store this data in a .env file to prevent hacking attempts. It is important to keep this data local and not push it to a git repository. 
Failure to do so may result in leaked secret keys being inadvertently exposed. your developer didn't

**4**I must admit, I was truly impressed by the complexity of this code! The overloaded hook implementation using useState and useEffect caught my attention, and he seemed to lack understanding of other important hooks such as useMemo, useRef, or useLayoutEffect.
As we are aware, improper usage of hooks can lead to unnecessary re-rendering and a decrease in site performance. I noticed that the use of useContext for managing global state may not be optimal for performance.
In order to reduce re-rendering and improve efficiency, it might be beneficial to consider alternative solutions such as Zustand or Redux instead of relying solely on useContext.

Additionally, assets were not utilized effectively. The images appear oversized in comparison to the area they are being used for. Consider reducing the image size manually or automatically. When utilizing Next.js (which operates on SSR), optimize image size by utilizing the "Image" tag provided by Next.js.

The creation of a gradient image seems unnecessary and inefficient. Creating a gradient using CSS would be both simpler and quicker for website loading compared to loading an image.
![4-gradient](https://github.com/user-attachments/assets/72f4f4ae-624e-4e27-a484-8d291a9630bd)
![4-largeImg](https://github.com/user-attachments/assets/6d9e74bf-2afc-41ae-ba6f-2dbc3777f51e)
![4-responsive1](https://github.com/user-attachments/assets/8986fe38-8f78-4b54-a446-65ab054b2251)
![4-responsive2](https://github.com/user-attachments/assets/2c0f66ff-91bd-4e7e-80c6-ff8b2df223e5)
![4-useeffect](https://github.com/user-attachments/assets/ee901537-78e8-429a-af02-e47e75ffcfe9)

**Comment by Crypto-zombie** [comment]
Leaked scecrete data.
![3-cms-key](https://github.com/user-attachments/assets/0a955f41-3da1-44b0-8903-8b485bb7076b)
![3-firebase](https://github.com/user-attachments/assets/8038c118-49b7-4344-bc40-2651c1fbf93a)

**Comment by Crypto-zombie** [comment]
And one more point, there.
I couldn't understand why @manu72143 blocked me. I just wanted to know the reason.

**Comment by sufyanbaig-ai** [comment]
Ok let me check. I'll get back you after reviewing
Can u pls share ur whatsapp numberc

**Comment by Crypto-zombie** [comment]
Thank you but I just wanted to contribute and prove myself.
If you can contact with James Fry of bluefrontier, ask him why he blocked me!
What is my wrong? I can't understand why he did.

**Comment by sufyanbaig-ai** [comment]
Can we schedule a call?

**Comment by Crypto-zombie** [comment]
No thanks, I want to meet only  James Fry.

**Comment by sufyanbaig-ai** [comment]
Awesome, thanks for the update!

**Comment by Crypto-zombie** [comment]
Did you develop this code and work as frontend developer in bluefrontier?

**Comment by sufyanbaig-ai** [comment]
Yes, I did.

**Comment by Crypto-zombie** [comment]
Can you contact with James Fry?

**Comment by sufyanbaig-ai** [comment]
Yes, I will.

**Comment by sufyanbaig-ai** [comment]
I can help u with update and changing your react app

**Comment by Crypto-zombie** [comment]
I must clarify that this project is not mine. My intention was simply to demonstrate my expertise and regain my honor.
Not scammer, not jonior developer!!!!!!!!!!!!!

**Comment by sufyanbaig-ai** [comment]
I agree with you. do you want to see my Upwork profile?

**Comment by sufyanbaig-ai** [comment]
https://upwork.com/freelancers/muhammadawaisullah?mp_source=share

**Comment by Crypto-zombie** [comment]
haha, it's not you!

**Comment by sufyanbaig-ai** [comment]
Awais is my Elder Brother

**Comment by sufyanbaig-ai** [comment]
If you'd like, you can contact Awais directly on WhatsApp. I can share his
number with you. Alternatively, you can message him on Upwork. If you need
the link to his Fiverr profile, I can provide that as well.

**Comment by sufyanbaig-ai** [comment]
+92 322 5460430 is Awais's WhatsApp number. You can message him directly
and let him know that his brother, Sufyan, gave you his number
